### PR TITLE
Added validation event

### PR DESCRIPTION
**Pull request by Christoph-Wagner**
Forms and inputs have a validation event and tests for it. When/if this is accepted, I’ll add the documentation.

On inputs, the handler data is `name: String, errors: String[]`, for forms it’s an array of

```
{
  name: String,
  errors: String[],
  hasErrors: boolean
}
```

### CODE REVIEW

**Comment by justin-schroeder** [comment]
@Christoph-Wagner Thanks for this PR! I've been reading though and playing with it this morning, great work (and thanks for cleaning up a few little issues here and there). After reviewing I've got some thoughts and questions. Currently the form-level validation errors are emitted only on submit (infrequent) and the field-level events are emitted on every keypress (frequent) even if there are no changes. What are your thoughts on:

- Only emitting the validation event if there has been a change in the validation state of an input.
- Emitting a validation event on the form every time an input changes it's validation state.

That way you can know reliably that if you're receiving a validation event, something actually happened, and applying the event at the form level is really just a way to catch all the sub-events in one place rather than having a slightly different cause/effect.

For getting validation on submit, users could still bind to the [`submit-raw` event](https://vueformulate.com/guide/forms/#advanced-uses) and the the `FormSubmission` instance could easily get all existing validation messages.

If you think that API works, i'd be happy to merge this into a feature branch and help it get there.

**Comment by Christoph-Wagner** [comment]
Yeah, the inconsistency between form and input events slipped my mind over the weekend :/ Now that I’m thinking about it, it also makes little sense to have different objects being returned by the events.

Good point regarding the state-change, I’ll work on this a bit more.

**Comment by justin-schroeder** [comment]
@Christoph-Wagner awesome, thanks for jumping in. One way I considered this could be accomplished is at the input level using `shallowEqualObjects`  (in utils) to compare the error message state at the input level, emitting the event if there was a change and then calling an injected function from the form, so maybe the FormulateForm `provide()`s something like `formulateFieldValidation` that each input calls when it detects a change, and then the form submits events in turn.

**Comment by Christoph-Wagner** [comment]
I currently have a problem writing a test to catch this not working:

```js
it('doesn’t emit a validation event if the validation state didn’t change', async () => {
    const wrapper = mount(FormulateInput, { propsData: {
        type: 'text',
        validation: 'min:5',
        // errorBehavior: 'live',
        value: '',
        name: 'testinput',
      } })
    await flushPromises()
    const validationEvents = wrapper.emitted('validation')
    expect(validationEvents.length).toBe(1)
    wrapper.find('input').trigger('blur')
    await flushPromises()
    expect(validationEvents.length).toBe(1)
  })
```

This passes, even when I comment out the code that checks if the errormessages are the same.

**Comment by justin-schroeder** [comment]
In this case the validation state did change. no error -> error. Blur doesn't change the error state, it only changes the visibility of the errors. No changes took place on the `model` after `const validationEvents = wrapper.emitted('validation')` so the validationEvents in reference are the same.

**Comment by Christoph-Wagner** [comment]
Yeah, just realized that myself. Which brings me to my next question, should the validation event happen on actual validation or follow the rules of `errorBehavior`?

**Comment by justin-schroeder** [comment]
It’s a solid question...my inclination would be to do it on actual validation and ignore error-behavior since that gives people an “eject” mechanism from the behavior if they need to do other things, but maybe we should add a “visibility” property to the errorObject that is the payload of the validation event

**Comment by Christoph-Wagner** [comment]
So emitting the same validation event (just with `visibility` changed) again when the visibility changes? That seems a bit hacky to me ;)

**Comment by justin-schroeder** [comment]
Fair, would you just emit without the visibility?

**Comment by Christoph-Wagner** [comment]
That would be the easiest option, but it feels a bit weird to me. How does a second event like `validation-messages-updated` sound?

**Comment by justin-schroeder** [comment]
I think a good middle-ground is:

- `@validation` fires any time an input's validation error message state changes, both input and form level. (shallowEqualObjects on messages)
- `@error-visibility` fires anytime the validation visibility changes on an input (input only)

**Pull request merged**
