### PR TITLE
WIP: Accessibility: Add `aria-describedby` if help text or errors are given

### LINKED ISSUE #30: Accessibility: Make `label` mandatory && link help and error messages
Hello,

Thanks for creating this library. Looks refreshing. I did some testing and found some accessibility problems with your current structure:

- By default, `<label>`is disabled. A label is the only way for users of assistive technology to know what input they should enter; it should, therefore, be a required prop
- The help text needs to be associated with the input using [aria-describedby](https://developer.paciellogroup.com/blog/2018/09/describing-aria-describedby/). Otherwise, there is no way to know input and text belong together
- Same goes for error messages. 

I’m a maintainer of an inclusive component library (https://github.com/tournantdev/ui/). [This is our input component](https://github.com/tournantdev/ui/blob/master/packages/input/src/index.vue), in which these points are handled. If you like, I can help out with solving these issues. :) 

And a mostly unrelated question: Is it possible to conditionally display validation messages? E.g. if an e-mail is required can I only show the required message and not that is the wrong format? 

Best wishes,
Oscar

### PR DESCRIPTION
**Pull request by ovlb**
Hey,

here’s a first draft to fix #30 

I got it working for text-like inputs and the help text. But I’m having kind of a hard time to get it to work for the errors, as the `visibleErrors` are determined in FormulateErrors.vue and FormulateInput (which has to orchestrate all the attributes) does not know about it. 

There are a couple of ways that come to mind how to solve this. Emitting an event in a watcher if the length of `visibleErrors` changes from 0 to >0. Or moving the visibility logic up to FormulateInput. Or maybe setting a property on `this.$formulate`?
Do you have any preferred way?

Regarding label: Changing label to be a required prop would be a breaking change and should probably not be introduced in a minor release. I would a `console.warn` call to warn implementors that they _should_ add a label if none is given. It could be changed to be required in 3.0.

Sorry for keeping you waiting for so long!

Oscar

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Awesome, thank you @ovlb, I'll review this soon.

I agree that making the label a required prop is probably not the best move at the moment since it would be largely breaking. There are also use cases for inputs where a label probably shouldn't be required, and other accessible options used instead (like `aria-label`), so some consideration should be given to those edge cases to.

**Comment by ovlb** [comment]
@justin-schroeder We could add a boolean prop `labelIsVisible` (defaults to `true`) and if this is passed as `false` add `aria-label` to the input instead of rendering the `label` element. 

I also need to have a second look at how to handle this for checkboxes and radio inputs.

**Comment by justin-schroeder** [comment]
@ovlb yes, something like that would work well. Additionally, your concerns about accessing the error messages is mostly resolved in the `feature/scoped-slots` branch which will be merged into this once more testing has been added, but essentially that branch is starting the good work of canonizing the `context` object and using that exclusively for nearly all functionality so there is a well-known object available for scoped slots.

There's a documentation branch you can checkout for more information on those changes:

https://vueformulatecom-org2yqm40.now.sh/guide/inputs/slots/

**Comment by ovlb** [comment]
Ah, nice! I will work on the label in the meantime.

**Comment by justin-schroeder** [comment]
@ovlb Thanks for your work on this one. I've used the `aria-describedby` from this in PR #85 to be launched in `2.3.0` when it help text is applied. I think we can do a lot more on accessibility though! I'd love more help on that. Since this is a bit stale as a WIP I'm going to close it as a PR for now.

**Pull request closed without merging**
