### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by chindit**
This PR add french translations.

Maybe there still will be some minor adjustments to make, but the essential is done.

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Merci beaucoup!

This is perfect! So i'm still considering how to handle multi-lingual support. I would love to support [vue-i18n](https://kazupon.github.io/vue-i18n/) but it's unclear to me how exactly that integrates with package maintainers. I certainly dont’t want i18n to be a requirement of the package, but if someone chooses to use it on their own site, we should support it.

I'm going to leave this open while I look into this! If there are any adjustments please add them as necessary.

**Comment by justin-schroeder** [comment]
Hi @chindit, There are 2 new validation rules that will ship in version 2.2.0: ends_with and starts_with. Would you mind adding those translations so it has full coverage? You can see them here:

https://github.com/wearebraid/vue-formulate/blob/release/2.2.0/src/locales/en.js#L178
https://github.com/wearebraid/vue-formulate/blob/release/2.2.0/src/locales/en.js#L95

**Comment by chindit** [comment]
Ok, I'll update translations next week.

As how vue-formulate should handle translations, I think the best way is to set language in the configuration options.

**Comment by chindit** [comment]
Given your work on translations, is this PR still relevant?

**Comment by justin-schroeder** [comment]
> Given your work on translations, is this PR still relevant?

@chindit not specifically this one, I was planning on closing it and asking if you’d be willing to pick it up on the vue-formulate-i18n package there your French translation was merged.

**Comment by chindit** [comment]
Yes, of course.
I saw there was a missing translation in French.

I'll make a PR next week on the new repo to fix this.

**Pull request closed without merging**
