### PR TITLE
Add a modelHook on FormulateInput, available through FormulateForm's schema too

### PR DESCRIPTION
**Pull request by gahabeen**
Would provide for #161 and #67.

I've implemented it as discussed. 
Also added tests cases on FormulateInput as well as FormulateForm, including some for both use cases stated above.

This should open a new road to build tiny utility plugins 😃

(Code is super simple. Tests should explain properly how to use it.)

### CODE REVIEW

**Comment by justin-schroeder** [comment]
This is great again @gahabeen. Although I do have more thoughts on this one. I think we need to make it similar to the classes and slots system where these models can be globally applied and overridden based on various context details. That allows for plugin authors to easily roll apply their own logic. Additionally, these globals should probably allow `n` hooks so multiple plugins can expose multiple hooks on the same hook point, almost like middleware. My thought is to create a new structure at the config level called `hooks` (in addition to a prop system like it is exposed in this PR)

```vue
Vue.use(VueFormulate, {
  hooks: {
    model: [],
    schema: [],
    schemaNode: []
    // ... other things we think up
  }
})
```

The prop equivalents would be similar to the class system, `model-hook`, `schema-hook`, `schema-node`...etc

**Comment by gahabeen** [comment]
Seems even better to me!
I'll let you iterate on it then.
Let me know if you need a hand.

**Comment by gahabeen** [comment]
I actually gave it a go and implemented a hooks oriented solution on my plugin [`vue-formulate-extended`](https://github.com/gahabeen/vue-formulate-extended). I've also added tests and re-organized the plugin to have a stable version.

You can check out the helper class [Hooks.js](https://github.com/gahabeen/vue-formulate-extended/blob/master/src/libs/hooks.js) as well as how I implemented them within the [components](https://github.com/gahabeen/vue-formulate-extended/tree/master/src/components) and the [configuration within VueFormulate](https://github.com/gahabeen/vue-formulate-extended/blob/master/src/index.js).

I've so far built [3 features](https://github.com/gahabeen/vue-formulate-extended/tree/master/src/features à thanks to the hooks.
I think there is still lots of place for improvements but I think it's already pretty sorted and stable.

If that can give you some ideas for the implementation.

**Comment by gahabeen** [comment]
I think we can close this for now as the discussion is still open and I already have a solution through the extended plugin I made.

**Pull request closed without merging**
