### PR TITLE
adds nuxt module to source files and build process

### PR DESCRIPTION
**Pull request by andrew-boyd**
Start of the Nuxt module.  Overall it's very simple - which is nice. As I mentioned, I was unable to get a locale imported and registered - no errors but it wouldn't stick - so I'd love to chat about making sure plugin registrations are supported and also how we should best approach that. importing Vue Formulate plugins in the nuxt.config.js and passing them through the options feels dirty to me - but if that's the way then that's the way.

### CODE REVIEW

**Comment by andrew-boyd** [comment]
Ok, updates on this:

- all config is now handled by an optional `formulate.config.js` file which will be imported for you
- by default there is no config, but you can either add `forumlate.config.js` to your `srcDir` or you can provide a `configPath` option to the module and point it to a different location.
- your config file should export a javascript object which is used in the `Vue.use()` registration for Vue Formulate.

**Review by justin-schroeder — COMMENTED** [review]
Is `dist/nuxt/plugin.js` a blind spot in the build process? Just reading the `build:nuxt` it seems it only "compiles" `/nuxt/index.js` and not the plugin. Also, perhaps we dont need to perform that copy at all since the `nuxt/dist/index.js` `addPlugin` could point back a directory or two to the original.

Curious on your thoughts about that.

**Comment by andrew-boyd** [comment]
Yeah, I'm down for simplifying it. none of it "needs" to be minified because it's all so small anyway so you could just keep everything in the `/nuxt` directory at the project root and point directly to that.

**Comment by justin-schroeder** [comment]
yeah good point, also these are only run on the server so minification doesnt provide much value. Let's kill that and remove the underscore/mangle. You might still want the "build" process though so you can put the `nuxt/index.js` into `dist/nuxt/index.js`. The `dist` directory should be able to be deleted and recompiled each time we run build

**Comment by andrew-boyd** [comment]
Ok, but functionally it would act as an unchanged duplicate. This would mean someone could import `@braid/vue-formulate/nuxt` or `@braid/vue-formulate/dist/nuxt` and it wouldn't matter.

I'll modify this.

**Comment by justin-schroeder** [comment]
oh...i thought it was in `/dist` for some kind of module mapping reasons. yeah, if we're making people import from `@braid/vue-formulate/dist/nuxt` lets kill the `dist` all together and just map them to the raw source. cleaner import then too!

**Comment by andrew-boyd** [comment]
Great! Yeah currently we can point to which _files_ should be entry points in the dist directory, but the same is not true for "make the `dist` directory the import root" which would be nice. Apparently, that's a thing in node 13+. Something to look forward to.

https://stackoverflow.com/questions/30302747/root-directory-in-package-json

**Pull request merged**
