### PR TITLE
Nanoid update

### PR DESCRIPTION
**Pull request by kswedberg**
Small change, updating nanoid dependency to 3.x and changing imports to use the named export.

It's not vue-formulate's fault, but when I install another dependency that uses nanoid 3.x (such as @nuxt/storybook or mocha), vue-formulate chokes on the nanoid import. The `yarn.lock` seems to point to the correct nanoid version when I run `yarn why nanoid`but I got an error anyway that nanoid is not a function, due to version 3 switching from default export to named export.

### CODE REVIEW

**Comment by kswedberg** [comment]
Hmmm. Strange that the checks failed. When I ran Jest tests locally they all passed. Also successfully ran cypress tests locally

**Comment by kswedberg** [comment]
Ah, I see. Looks like your cypress ci test needs a `--key` argument: 

`error: option '-k, --key <record-key>' argument missing`

**Comment by last-partizan** [comment]
@justin-schroeder How about merging this and releasing? It's small but useful change.

**Comment by justin-schroeder** [comment]
nanoid is now removed entirely

**Pull request closed without merging**
