### PR TITLE
fix: index undefined in leaf's key

### PR DESCRIPTION
**Pull request by atharva3010**

### CODE REVIEW

**Comment by justin-schroeder** [comment]
Close, although we have a failing test on this for mutating the schema. This fixed my dumb bug of not having the index there, but I think the issue is we can't actually use the index here...grrr. the only way to make this work perfectly (i think) is to hash/collapse any `children` and include that in the key. That way if youre not changing content, using index is safe, but if you are changing content it will re-hydrate. This will certainly cause performance issues though, so im open to other suggestions too.

Deterministic auto-generated unique ids that dont use an index are just really hard. Technically they're impossible if we dont account for content

**Comment by atharva3010** [comment]
> Deterministic auto-generated unique ids that dont use an index are just really hard. Technically they're impossible if we dont account for content

How so?
Btw, what is the need of including an index here? Can't we just use a random uuid?

**Comment by justin-schroeder** [comment]
normally this problem bites us and we cannot use randoms because they are used for `id` attribute and that breaks SSR re-hydration (like on Nuxt). Its a common problem (see: https://github.com/facebook/react/issues/5867) but in this case since we're not using these keys as ids we might be able to get away with not even providing a key for non-formulate items. We definitely need a unique key for formulate inputs though.

**Comment by justin-schroeder** [comment]
This is now fixed in the `release/2.5` branch

**Pull request closed without merging**
